"""Update Cattle model 2

Revision ID: 53ec9ff5d03b
Revises: 652e5c0cd54b
Create Date: 2023-06-06 23:55:43.552764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53ec9ff5d03b'
down_revision = '652e5c0cd54b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.drop_column('birth_year')

    # ### end Alembic commands ###
