"""cattle model further updated

Revision ID: 8a68ad277bf4
Revises: cbeb28ca23a9
Create Date: 2023-06-08 09:51:17.329945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a68ad277bf4'
down_revision = 'cbeb28ca23a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
