"""cattle_database_is_pregnant

Revision ID: cbeb28ca23a9
Revises: 53ec9ff5d03b
Create Date: 2023-06-07 13:35:09.494611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbeb28ca23a9'
down_revision = '53ec9ff5d03b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_pregnant', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.drop_column('is_pregnant')

    # ### end Alembic commands ###
